# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabio/Documents/Beat_The_Beat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabio/Documents/Beat_The_Beat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/Beat_The_Beat/CMakeFiles /home/fabio/Documents/Beat_The_Beat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/Beat_The_Beat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Beat_The_Beat

# Build rule for target.
Beat_The_Beat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Beat_The_Beat
.PHONY : Beat_The_Beat

# fast build rule for target.
Beat_The_Beat/fast:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/build
.PHONY : Beat_The_Beat/fast

Conductor.o: Conductor.cpp.o

.PHONY : Conductor.o

# target to build an object file
Conductor.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Conductor.cpp.o
.PHONY : Conductor.cpp.o

Conductor.i: Conductor.cpp.i

.PHONY : Conductor.i

# target to preprocess a source file
Conductor.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Conductor.cpp.i
.PHONY : Conductor.cpp.i

Conductor.s: Conductor.cpp.s

.PHONY : Conductor.s

# target to generate assembly for a file
Conductor.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Conductor.cpp.s
.PHONY : Conductor.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameObject.o: GameObject.cpp.o

.PHONY : GameObject.o

# target to build an object file
GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/GameObject.cpp.o
.PHONY : GameObject.cpp.o

GameObject.i: GameObject.cpp.i

.PHONY : GameObject.i

# target to preprocess a source file
GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/GameObject.cpp.i
.PHONY : GameObject.cpp.i

GameObject.s: GameObject.cpp.s

.PHONY : GameObject.s

# target to generate assembly for a file
GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/GameObject.cpp.s
.PHONY : GameObject.cpp.s

Inputs.o: Inputs.cpp.o

.PHONY : Inputs.o

# target to build an object file
Inputs.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Inputs.cpp.o
.PHONY : Inputs.cpp.o

Inputs.i: Inputs.cpp.i

.PHONY : Inputs.i

# target to preprocess a source file
Inputs.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Inputs.cpp.i
.PHONY : Inputs.cpp.i

Inputs.s: Inputs.cpp.s

.PHONY : Inputs.s

# target to generate assembly for a file
Inputs.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Inputs.cpp.s
.PHONY : Inputs.cpp.s

MagicView.o: MagicView.cpp.o

.PHONY : MagicView.o

# target to build an object file
MagicView.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/MagicView.cpp.o
.PHONY : MagicView.cpp.o

MagicView.i: MagicView.cpp.i

.PHONY : MagicView.i

# target to preprocess a source file
MagicView.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/MagicView.cpp.i
.PHONY : MagicView.cpp.i

MagicView.s: MagicView.cpp.s

.PHONY : MagicView.s

# target to generate assembly for a file
MagicView.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/MagicView.cpp.s
.PHONY : MagicView.cpp.s

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Main.cpp.s
.PHONY : Main.cpp.s

Note.o: Note.cpp.o

.PHONY : Note.o

# target to build an object file
Note.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Note.cpp.o
.PHONY : Note.cpp.o

Note.i: Note.cpp.i

.PHONY : Note.i

# target to preprocess a source file
Note.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Note.cpp.i
.PHONY : Note.cpp.i

Note.s: Note.cpp.s

.PHONY : Note.s

# target to generate assembly for a file
Note.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Note.cpp.s
.PHONY : Note.cpp.s

NoteTextEvent.o: NoteTextEvent.cpp.o

.PHONY : NoteTextEvent.o

# target to build an object file
NoteTextEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/NoteTextEvent.cpp.o
.PHONY : NoteTextEvent.cpp.o

NoteTextEvent.i: NoteTextEvent.cpp.i

.PHONY : NoteTextEvent.i

# target to preprocess a source file
NoteTextEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/NoteTextEvent.cpp.i
.PHONY : NoteTextEvent.cpp.i

NoteTextEvent.s: NoteTextEvent.cpp.s

.PHONY : NoteTextEvent.s

# target to generate assembly for a file
NoteTextEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/NoteTextEvent.cpp.s
.PHONY : NoteTextEvent.cpp.s

Resources.o: Resources.cpp.o

.PHONY : Resources.o

# target to build an object file
Resources.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Resources.cpp.o
.PHONY : Resources.cpp.o

Resources.i: Resources.cpp.i

.PHONY : Resources.i

# target to preprocess a source file
Resources.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Resources.cpp.i
.PHONY : Resources.cpp.i

Resources.s: Resources.cpp.s

.PHONY : Resources.s

# target to generate assembly for a file
Resources.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Resources.cpp.s
.PHONY : Resources.cpp.s

Stave.o: Stave.cpp.o

.PHONY : Stave.o

# target to build an object file
Stave.cpp.o:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Stave.cpp.o
.PHONY : Stave.cpp.o

Stave.i: Stave.cpp.i

.PHONY : Stave.i

# target to preprocess a source file
Stave.cpp.i:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Stave.cpp.i
.PHONY : Stave.cpp.i

Stave.s: Stave.cpp.s

.PHONY : Stave.s

# target to generate assembly for a file
Stave.cpp.s:
	$(MAKE) -f CMakeFiles/Beat_The_Beat.dir/build.make CMakeFiles/Beat_The_Beat.dir/Stave.cpp.s
.PHONY : Stave.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Beat_The_Beat"
	@echo "... Conductor.o"
	@echo "... Conductor.i"
	@echo "... Conductor.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameObject.o"
	@echo "... GameObject.i"
	@echo "... GameObject.s"
	@echo "... Inputs.o"
	@echo "... Inputs.i"
	@echo "... Inputs.s"
	@echo "... MagicView.o"
	@echo "... MagicView.i"
	@echo "... MagicView.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Note.o"
	@echo "... Note.i"
	@echo "... Note.s"
	@echo "... NoteTextEvent.o"
	@echo "... NoteTextEvent.i"
	@echo "... NoteTextEvent.s"
	@echo "... Resources.o"
	@echo "... Resources.i"
	@echo "... Resources.s"
	@echo "... Stave.o"
	@echo "... Stave.i"
	@echo "... Stave.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

